### ISSUE TITLE
bc.encode输出分类预测结果

### ISSUE THREAD

**Issue by zylhub** [zylhub/bert-as-service#1]
默认情况下，bert-as-service提供句子的特征编码。如果期望提供分类预测结果呢？

参考此issues 修改代码 输出分类预测[#213 How to get probability from a finetuned classify model ](https://github.com/hanxiao/bert-as-service/issues/213)

整体思路：
1. 加载预训练模型的时候 加载分类层的权重和bias（⚠️不要添加初始化方法）
2. 添加分类预测层
3. 添加相关参数

> 如果在bert训练过程对模型有过修改，应该在 [server/bert_serving/server/bert](https://github.com/zylhub/bert-as-service/tree/master/server/bert_serving/server)中替换为对应代码

**Comment by smartcatdog** [comment]
> 默认情况下，bert-as-service提供句子的特征编码。如果期望提供分类预测结果呢？
> 
> 参考此issues 修改代码 输出分类预测[#213 How to get probability from a finetuned classify model ](https://github.com/hanxiao/bert-as-service/issues/213)
> 
> 整体思路：
> 
> 1. 加载预训练模型的时候 加载分类层的权重和bias（⚠️不要添加初始化方法）
> 2. 添加分类预测层
> 3. 添加相关参数
> 
> > 如果在bert训练过程对模型有过修改，应该在 [server/bert_serving/server/bert](https://github.com/zylhub/bert-as-service/tree/master/server/bert_serving/server)中替换为对应代码

Firstly, thanks for your help to deploy bert to realize the classification task by bert-as-service, may i for your help to how to write client for prediction after serving start  by using bert-as-service. 
Thank you ~

**Comment by smartcatdog** [comment]
got it，3Q~
